### ISSUE TITLE
Upload Informational sheets surrounding common algorithms

### ISSUE THREAD

**Issue by gtallen1187** [HealthAPI/helmet#37]
@matthewplunkett - can you upload some information components on a few of the more common algorithms?  i think the list below would likely be a good starting point, but please feel free to alter it as you see fit:
- [x] CMS HCC
- [x] JHU ACG
- [x] NYU ED
- [x] [PRONE Score](http://qualitysafety.bmj.com/content/early/2015/04/08/bmjqs-2014-003834.full)
  - This one seems really interesting.  This model is said to accurately predict the likelihood of negative patient satisfaction ratings for a given doctor, based on widely collected administrative data.  Seeing as how important those scores are in reimbursement (specifically for STAR measurements), if this model is valid, it could be a nice differentiator.
- [x] something surrounding heart failure
- [x] something surrounding End-Stage Renal Disease

Just a few thoughts for a starting point, but the more the better. :sunglasses:

**Comment by matthewplunkett** [comment]
@gtallen1187 just saw this -- i'll post some stuff today after work. never heard of PRONE score until now, but with CMS basing 30% of performance score on HCAHPS survey I would imagine this would interest people.

**Comment by matthewplunkett** [comment]
@gtallen1187  Put some background information on a few in [docs](https://github.com/HealthAPI/helmet/tree/docs/docs/risk_models), some more detailed than others based on public availability (and legality). Once we get a better idea of the direction we want to head in and I have a better understanding of what our capabilities are, I can focus the content and expand it. I found the [Framingham Heart risk models](https://github.com/HealthAPI/helmet/tree/docs/docs/risk_models/Framingham_Heart_Study) to be particularly interesting and complete.
