### ISSUE TITLE
next steps

### ISSUE THREAD

**Issue by gtallen1187** [HealthAPI/helmet#40]
@HealthAPI/owners,

Now that @matthewplunkett has done the grunt work of getting all of this algorithm documentation into this repo, i think it makes sense to start talking about next steps.

i've put together a first draft of what i think would be the next logical steps in this situation, however this is simply intended to give us something to work from; happy to discuss these in more detail wherever needed, and obviously would love some input here as well.
- prioritize these algorithms based on business use case.  algorithms most closely tied to financial reimbursement would rank higher on the priority list than those only used for reimbursement models in a few markets.
- simultaneously, we should create another prioritization list based on implementation complexity.
  - @boxuancui, @woo91rmgh - what is the most logical way to group these algorithms?  complexity?  language?  input requirements?
- once both of these lists are done, we should cross-walk them and figure out which ones to fully implement first.

I think the full implementation of these models is going to be the tough part.  In terms of the actual API, i don't think that part will be too complicated.  The majority of the work will consist of defining inputs that work across all of the models.  Once we have that, we would need to figure out how the inputs write to the DB, and then that kind of wraps it up.

anyways, this is my idea for next steps.  any feedback here would be great.

**Comment by boxuancui** [comment]
@HealthAPI/owners Is there any market research done for coverage & scope of the algorithms? For example, `algorithm 1` solves `problem 1`, which is relevant to 70% of people in the US, while `algorithm 2` solves `problem 2`, which covers only 5% of people in the US. I would prioritize on those metrics. I might be completely off track due to insufficient knowledge in this space.

**Comment by gtallen1187** [comment]
@boxuancui 
cc: @HealthAPI/owners 

solid questions, and you're not off track at all.

I'm not sure if there is any _real_ market analysis done on algorithm coverage across the industry.  At least, not to the level of market research that you would want to have in this situation.  And definitely not on par with what you would have worked with on a case back in your glory days on the 7th floor.

That being said, I know that when i was working at my last company with @matthewplunkett, i could definitely give you a lot of these answers just from experience working in the field.  We spent a large amount of our time analyzing different programs from different insurers across the state, and i could definitely prioritize this list just from which algorithms i know to be prevalent versus which ones i know are less significant.

I've also been out of the game for almost 8 months now, so i would be cautious that my knowledge may be outdated.  i'm sure @matthewplunkett or @glfernandes88 could contribute here though.

i don't think we'll be able to come up with precise metrics like "percent coverage of algorithm 1 across insurance companies offering _x_ products in _y_ markets", but if the end goal is simply a prioritized list, i'm confident we can create a workable list that would hold up to scrutiny.

who knows, maybe @woo91rmgh might even help :disappointed:

**Comment by glfernandes88** [comment]
A simple way to answer your question is to target the population you're
building the algorithm towards. For example, HCC is only relevant towards
the aging Medicare population which might be around ~ 50 Million
beneficiaries at this point (16-20%)

On Tue, Jul 7, 2015 at 7:42 PM, Greg Allen notifications@github.com wrote:

> @boxuancui https://github.com/boxuancui
> cc: @HealthAPI/owners https://github.com/orgs/HealthAPI/teams/owners
> 
> solid questions, and you're not off track at all.
> 
> I'm not sure if there is any _real_ market analysis done on algorithm
> coverage across the industry. At least, not to the level of market research
> that you would want to have in this situation. And definitely not on par
> with what you would have worked with on a case back in your glory days on
> the 7th floor.
> 
> That being said, I know that when i was working at my last company with
> @matthewplunkett https://github.com/matthewplunkett, i could definitely
> give you a lot of these answers just from experience working in the field.
> We spent a large amount of our time analyzing different programs from
> different insurers across the state, and i could definitely prioritize this
> list just from which algorithms i know to be prevalent versus which ones i
> know are less significant.
> 
> I've also been out of the game for almost 8 months now, so i would be
> cautious that my knowledge may be outdated. i'm sure @matthewplunkett
> https://github.com/matthewplunkett or @glfernandes88
> https://github.com/glfernandes88 could contribute here though.
> 
> i don't think we'll be able to come up with precise metrics like "percent
> coverage of algorithm 1 across insurance companies offering _x_ products
> in _y_ markets", but if the end goal is simply a prioritized list, i'm
> confident we can create a workable list that would hold up to scrutiny.
> 
> who knows, maybe @woo91rmgh https://github.com/woo91rmgh might even
> help [image: :disappointed:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HealthAPI/helmet/issues/40#issuecomment-119375174.

## 

[image: eClinicalWorks] http://www.eclinicalworks.com

Glen Fernandes / Healthcare Enthusiast
716-390-2746/ glen.fernandes@us.pwc.com

[image: Facebook] https://www.facebook.com/profile.php?id=15725555
[image: Twitter] https://twitter.com/oh_raspberries [image:
Linkedin] http://www.linkedin.com/in/glenfernandes/ [image: Skype]
http://glen.fernandes

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination,
distribution, copying or the taking of any action in reliance on the
information herein is prohibited. E-mails are not secure and cannot be
guaranteed to be error free as they can be intercepted, amended, or
contain viruses. Anyone who communicates with us by e-mail is deemed
to have accepted these risks. Company Name is not responsible for
errors or omissions in this message and denies any responsibility for
any damage arising from the use of e-mail. Any opinion and other
statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the
company.

**Comment by boxuancui** [comment]
@glfernandes88 Do you happen to have a physical summary somewhere? or everything is sitting in your brain? I think it would be extremely helpful to compile that information and make it the starting point to build algorithms.

**Comment by boxuancui** [comment]
@gtallen1187 please send @woo91rmgh glitter bombs. :boom:

**Comment by gtallen1187** [comment]
i'm in agreement with @glfernandes88 here, and would suggest potentially taking it one step further to align not only with the target population, but additionally the target payers who service this population.

I'm gonna try to put something together that we can potentially staple on to whatever glen is able to potentially wrangle up.
