### ISSUE TITLE
initial target clients

### ISSUE THREAD

**Issue by gtallen1187** [HealthAPI/helmet#42]
@HealthAPI/owners,

so i was speaking to a friend of mine last night about this, and he asked me "who would be your first ten clients?"  While i had a generic answer for this, i think it's important that we actually have a concrete list of potential clients who we believe would purchase this solution.  I think it's important that we have a solid answer to the question "name 10 people who would buy this right now", so this is my attempt at providing that answer.

In general terms, our target market could be described as such:

> Any company or individual involved in the development of healthcare applications

As the product evolves and becomes more robust, our client list will change as well.

Initially, I think our best entry tactic would be to target smaller healthcare app organizations and compete on price point.  For companies like **[dr chrono](https://www.drchrono.com/)**, **[iQuartic](http://iquartic.com/)**, and **CareX**, it will likely not be cost-efficient for them to create and manage their own datascience department, especially at this stage in their company's lifecycle.  However, their need to implement these algorithms is no smaller than their more mature competitors; payers are demanding it, and the consumer will follow.

As our product grows, so too will our potential market.  The traction we gain from initially targeting smaller organizations will allow us to expand our algorithm set and product features.  At a certain point in our growth, we will be able to transition away from a cost-competitive model and into a more value/quality model.

Initially, companies like [NextGen](https://www.nextgen.com/Info/Top-Rated-EHR), [athenahealth](http://landing.athenahealth.com/g/improvecare), and [eClinicalWorks](https://www.eclinicalworks.com/) will likely try and pursue a longer-term strategy by building their own in-house capabilities surrounding these algorithms and models (which is why they would be bad _initial_ clients).  However, as time goes by and our offering becomes more robust, the dynamic will change here.  For these types of companies, the **_cheapest**_ option will likely always be in-house.  However, eventually i think we will become the **_best**_ option - our offerings will exceed what they are capable of building themselves.  While these companies are competing which each other on the various other aspects of their offerings, we can silently focus on building this highly-specialized capability uncontested.

anyways - let me know if this makes sense to all of yinz, or if you have any questions.  Happy to elaborate more wherever needed.

**Comment by gtallen1187** [comment]
@HealthAPI/owners 

also, if you want to see an example of a company with a similar business model, check out [TrueVault](https://www.truevault.com/).

**Comment by gtallen1187** [comment]
Here is a list of the [Top 100 EMR Companies](http://medicaleconomics.modernmedicine.com/medical-economics/content/tags/top100ehrs/top-100-ehr-companies-part-1-4) (in terms of revenue) from 2013.

Obviously, this list will have changed a bit since the date of publication.  But this should still provide a good starting point for compiling a list of potential clients.

**Comment by brendanf22** [comment]
@gtallen1187  - you said, "for companies like dr chrono, iQuartic, and CareX"... Can you describe what these companies are like? Are these "small EHR's?"

I think you told me there are non-EHR customers out there, too. Can you describe what those markets look like?

Lastly, do you know of any resources you can offer around industry lingo?

**Comment by gtallen1187** [comment]
@brendanf22 - yes, drchrono, CareX, and iQuartic are all examples of small, independent EHR companies.

regarding the non-EHR customers, i think that is a wide market, that merits a more in-depth response than this issue is intended for.  i'll upload some more content surrounding this.

re: healthcare lingo, i'm afraid i don't know of any resources better than what google can offer.  Here's a few highlights though:
- EMR/EHR - Electronic Medical Record, Electronic Health Record (same thing)
- CMS - Medicare (Centers for Medicare/Medicaid Services)
- ICD - International Classification of Diseases.  ICD-9 = ICD Version 9 (currently used system in the U.S.).  ICD-10 next version, to be implemented in the U.S. "soon" (deadline has been pushed back multiple times)
- MU - Meaningful Use.  This was the incentive program that prompted the widespread adoption of EMRs.
- P4P - Pay for Performance.  Shorthand that describes the increasingly popular provider reimbursement model being adopted across the industry.
- CQM - Clinical quality measures.  CQMs are often a component of an overall P4P program.

Just a start, but google seems to have some good resources here too.  here's a [decent one](http://www.academyhealth.org/files/publications/glossary.pdf) i found.

**Comment by brendanf22** [comment]
Nice, thanks Greg.

**Comment by gtallen1187** [comment]
@HealthAPI/owners,

I was able to snag some metadata from a market research report on the Electronic Medical Records industry, focusing on the industry's growth potential from 2015-2019.

This market research firm (www.researchandmarkets.com believe it or not :satisfied:) estimates a CAGR (comp annual growth rate) of 6.53% over that 5 year period.  Not sure how that stacks up against other industries, but that's definitely large enough to support what we're trying to do.

Back to the relevant stuff - they actually list out who they consider to be the top players in the market, as well as other "prominent" vendors as well:

# Key Vendors
- **Allscripts Healthcare Solutions**
- **Cerner**
- **eClinicalWorks**
- **Epic Systems**
- **McKesson**
- Medical Information Technology (**MEDITECH**)

### Other Prominent Vendor
- Acardia Healthcare
- Advanced Data Systems
- Allmeds
- Aprima Medical Software
- **Athenahealth**
  - Their CEO is [quite the personality](https://www.youtube.com/watch?v=lwF8SD1X0js)
- BIizmatics
- CareCloud
- ChartLogic
- CPSI
- CSC
- CureMD
- Dr First
- Emdeon
- e-MDS
- GE Healthcare
- **Greenway Medical Technologies**
  - These guys could literally fold any minute.
- Healthland
- Kareo
- Medent
- MedHost
- Meditab
- Medsphere Systems
- Merge Healthcare
- NEXTGEN Healthcare
- Nuesoft
- **Practice Fusion**
  - These guys actually offer their product completely free of charge to physicians.  Coincidentally, it's entirely cloud-based and they don't offer any type of on-premise data storage whatsoever....  I actually had a meeting once with BCBS of Texas in which Practice Fusion was there, and the type of questions they were asking really exposed what their true business model was. 
- Quadramed
- Sequel Systems
- **Siemens Healthcare Diagnostics**
  - These guys are actually worth paying attention to in the EMR market, not just the medical devices market anymore.
- SoapWare
- Streamline
- WebPT
- Wellsoft
- WRS Health

**Comment by gtallen1187** [comment]
closing this out for now, but we can keep this issue for reference later on.  I think we have what we're looking for here.
